name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for OIDC

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create short SHA
      id: short_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/sundai-stocks
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=v${{ github.run_number }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=${{ steps.short_sha.outputs.sha }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          DEBUG=False

    # Deploy only on main branch
    - name: Azure Login with OIDC
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Configure private registry access
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🔐 Configuring private GitHub Container Registry access..."
        
        # Configure registry credentials for the container app
        az containerapp registry set \
          --name stocks \
          --resource-group sundai \
          --server ghcr.io \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}
        
        echo "✅ Registry access configured"

    - name: Deploy to Azure Container Apps
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying secure image with runtime secrets..."
        
        # Update the container app with new image and environment variables
        az containerapp update \
          --name stocks \
          --resource-group sundai \
          --image ghcr.io/${{ github.repository_owner }}/sundai-stocks:latest \
          --set-env-vars \
            DASH_USERNAME="${{ secrets.DASH_USERNAME }}" \
            DASH_PASSWORD_HASH="${{ secrets.DASH_PASSWORD_HASH }}" \
            SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            NEWS_API_KEY="${{ secrets.NEWS_API_KEY }}" \
            DEBUG="False"
        
        echo "✅ Deployment completed successfully!"

    - name: Verify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🔍 Verifying deployment status..."
        
        # Show the current revision status
        az containerapp revision list \
          --name stocks \
          --resource-group sundai \
          --query '[0].{Name:name,Active:properties.active,CreatedTime:properties.createdTime,Image:properties.template.containers[0].image,TrafficWeight:properties.trafficWeight}' \
          --output table
        
        # Get the app URL
        APP_URL=$(az containerapp show \
          --name stocks \
          --resource-group sundai \
          --query 'properties.configuration.ingress.fqdn' \
          --output tsv)
        
        if [ ! -z "$APP_URL" ]; then
          echo "🌐 Application available at: https://$APP_URL"
        fi
        
        echo "📊 Deployment summary:"
        echo "- Image: ghcr.io/${{ github.repository_owner }}/sundai-stocks:latest"
        echo "- Build: v${{ github.run_number }}"
        echo "- Commit: ${{ steps.short_sha.outputs.sha }}"
        echo "- Registry: Private (ghcr.io)"
        echo "- Status: ✅ Deployed"